### ISSUE TITLE
Script halt due to "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by jacktan888** [DMTF/Redfish-Service-Conformance-Check#118]
Hi,
The test stopped due to TypeError while running to Assertion 6.1.8.1. Please see attachment for detail output. Please advice how to resolve it?

Thanks.

Jack Tan.
[ConformanceOutput.txt](https://github.com/DMTF/Redfish-Service-Conformance-Check/files/1996282/ConformanceOutput.txt)

**Comment by billdodd** [comment]
Jack,

It looks like the test run had a more fundamental problem connecting to your service. It was getting connection reset errors from the `/redfish`, `/redfish/v1/` and `/redfish/v1/$metadata` endpoints, so was unable to gather the service URIs to validate. From the beginning of your log:

```
Setting up Redfish Service Check Tool Revision: 01.05.17 : OpenPowerP9:172.31.56.169
OPERATIONAL ERROR: GET Request for /redfish FAILED with exeption: <class 'ConnectionResetError'>
Protocol version and Service Root uri could not be retrieved through '/redfish', assuming spec mandated values
OPERATIONAL ERROR: GET Request for /redfish/v1/odata FAILED with exeption: <class 'ConnectionResetError'>
OPERATIONAL ERROR: GET Request for /redfish/v1/ FAILED with exeption: <class 'ConnectionResetError'>

Collecting all relative uris from Service Root: /redfish/v1/
OPERATIONAL ERROR: GET Request for /redfish/v1/ FAILED with exeption: <class 'ConnectionResetError'>

Serializing SUT metadata document: /redfish/v1/$metadata ...
OPERATIONAL ERROR: GET Request for /redfish/v1/$metadata FAILED with exeption: <class 'ConnectionResetError'>
Unable to parse Service Metadata Document /redfish/v1/$metadata
```

Can you double-check the config information in the `SUTs` section of the `properties.json` file to be sure it is correctly specifying the target system? If that looks OK, you can then try accessing those endpoints with tools like curl or Postman to diagnose further.

**Comment by mraineri** [comment]
@jacktan888 any update on @billdodd's request?

**Comment by jacktan888** [comment]
Hi @billdodd @mraineri , the target was correctly set. 
This issue has been resolved by newly update  code.
