### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#123]
Is this code correct? Got exception and I do not see enough arguments either.

File "G:/_Redfish_git/Tools/Redfish-Service-Conformance/Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 1649, in Assertion_6_4_24
    log.assertion_log('line', "~ PATCH on Property %s of resource %s is a Read-only property according to its schema document %s, which might have been updated unexpectedly" % (prop, relative_uris[relative_uri]) )
TypeError: not enough arguments for format string

**Comment by billdodd** [comment]
Sorry for the delay in looking at this. I took a look today and it seems this was fixed via PR #124.

**Comment by mraineri** [comment]
@jbobzin-insyde can we close this out? Did the PR Bill reference address the issue?
