### ISSUE TITLE
False failure on Assertion 6.4.25

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Conformance-Check#132]
The tool tells me that Assertion 6.4.25 fails:

```
---> Assertion: 6.4.25

~ GET:/redfish/v1/CompositionService/ResourceBlocks/r001i06b/System/Processors/2 failed : HTTP status 200:OK, Expected statuses: [304]

~ GET /redfish/v1/CompositionService/ResourceBlocks/r001i06b/System/Processors/2 with If-None-Match provided an etag returned status 200:OK which indicates that this resource which does not allow PUT method might have been updated unexpectedly as a result of requesting a PUT method on it previously

Assertion Description: b'Services may support the PUT method to replace a resource in whole.  If a service does not implement this method, status code 405 shall be returned.'
<--- Assertion 6.4.25: FAIL
```

My apache log at that point shows that we did return 405. The assertion failed because a http_cached_GET afterward return 200 rather than a 304. But if I replace the http_cached_GET with an http_GET, it works. So it must be incorrectly using a cached response from when it did _not_ set the If-None-Match header to match the resource's eTag.

**Comment by billdodd** [comment]
@robrons96 - can you take a look at this? I think any of the assertions that make updates and then do a GET to check the results need to use http_GET rather than http_cached_GET.

**Comment by mraineri** [comment]
Should be fixed already in an older PR; closing. Please reopen if this is still an issue.
