### ISSUE TITLE
Bug in 6.5.6.10? Unauthorized

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#135]
There must be a bug in 6.5.6.10.  I send bad auth, below, and get the expected 401.

redfishtool -r localhost -u wrongid -p wrongpass raw GET /redfish/v1/Chassis/Rack1-Block1-Sled2
   redfishtool: Transport: Response Error: status_code: 401 -- Unauthorized
   redfishtool: raw: Error getting response

**BUT** From Conformance 6.5.6.10
Requesting GET /redfish/v1/Chassis/Rack1-Block1-Sled2 with invalid credentials for header authorization...
~ GET:/redfish/v1/Chassis/Rack1-Block1-Sled2 failed : HTTP status 200:OK, Expected statuses: [401]

**Comment by billdodd** [comment]
Looks like an issue similar to #132 related to the new caching feature. For this authz failure assertion, it should be using the regular self.http_GET() rather than self.http_cached_GET().

@robrons96 - FYI.

**Comment by robrons96** [comment]
Thanks for informing, fix will be added in today's meeting PR.

**Comment by mraineri** [comment]
@PhillipWatts1012 is this issue still present?

**Comment by mraineri** [comment]
Closing; this issue has been open a while and should be addressed now. Please reopen if the issue still persists.
