### ISSUE TITLE
Exceptions in test crash the test

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#148]
In order to get to a valid test run I could evaluate, I had to get around some crashes.

Redfish-Service-Conformance-Check/rfs_test/TEST_accountservice_schema.py
   createDummyAccount needs try except
    try:
        uri = relative_uris['Root Service_AccountService_Accounts']
    except:
        print ('Root Service_AccountService_Accounts not in relative_uris')
        return
------------------------------
WHAT IS THIS?
    for i in range(0, AccountLockoutThreshold):
        if not failAuthorization(self):
            assertion_status = log.WARN
            log.assertion_log('line', "~  Could not fail the authorization")
            return assertion_status
  File "/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/TEST_accountservice_schema.py", line 347, in Assertion_ACCO105
    for i in range(0, AccountLockoutThreshold):
NameError: name 'AccountLockoutThreshold' is not defined
------------------------------
/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/TEST_actioninfo_schema.py
    Assertion_ACTI104
THIS EXCEPTION NEEDS AN EXCEPTION
       assertion_status = log.WARN
        log.assertion_log('line', "Resource %s, is not found." % (relative_uris['Root Service_Systems']))
        return assertion_status
 line 53, in Assertion_ACTI104
    log.assertion_log('line', "Resource %s, is not found." % (relative_uris['Root Service_Systems']))
------------------------------

**Comment by billdodd** [comment]
@robrons - Can you take a look at these issues in the new accountservice and actioninfo modules?

Note that the second one (`NameError` on `AccountLockoutThreshold`) was already fixed in a PR last week.

Thanks

**Comment by robrons** [comment]
@PhillipWatts1012 @billdodd - A fix has been added for the mentioned issues and will be reviewed in todays meeting.

**Comment by mraineri** [comment]
@PhillipWatts1012 is this issue still present?

**Comment by mraineri** [comment]
Closing; this issue has been open a while and should be addressed now. Please reopen if the issue still persists.
