### ISSUE TITLE
Redfish API data format

### ISSUE THREAD

**Issue by nagvad** [DMTF/Redfish-Service-Conformance-Check#151]
Hello,
Does this tool expects data returned by Redfish API to be in "string" format ?

I see its failing to parse data if the data is in JSON format. Is there any command option to tell data type?

Thanks.

**Comment by mraineri** [comment]
@nagvad are you able to answer @billdodd's question?

**Comment by nagvad** [comment]
Sorry for the late response, I was out for few weeks. 

I will check Bill suggestion, closing the issue now.
