### ISSUE TITLE
Assertion 6.4.2.3 incorrectly fails

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Conformance-Check#155]
I'm getting a failure on assertion 6.4.2.3, claiming that ```HTTP status 200:OK with request header: OData-Version and incorrect value: 3.0 passed, which is an unexpected behavior```. But I instrumented by redfish server to log the client's request headers, and I only see Odata-Version of "4.0" being provided when this assertion is checked!

**Comment by billdodd** [comment]
This issue is due to the caching changes that were previously made. This assertion should not be using cached responses. I will update it.
