### ISSUE TITLE
Assertion 6.5.3 incorrectly requires HEAD support

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Conformance-Check#156]
The redfish spec says that supporting HEAD is optional. But if assertion 6.5.3 sees a 405 response, it gives this error message:

```HTTP status 405:Method Not Allowed, Expected statuses: [200]```

**Comment by billdodd** [comment]
@blakehilliard - I created PR #159 for this and tested as best as I could. But I don't have a real service that doesn't support HEAD. If you could test the PR on your service to confirm it fixes your issue that would be helpful.

**Comment by blakehilliard** [comment]
It still gives warning messages like this:

```~ HEAD:/redfish/v1 warning : HTTP status 405:Method Not Allowed, Expected statuses: [200]```

But then it says PASS for the overall status of the assertion.

**Comment by billdodd** [comment]
Great, thanks for checking. That's the behavior I was expecting. The warning in the log is the result of the way the `response_status_check()` method works.
