### ISSUE TITLE
Assertion numbers based on spec location no longer match

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Service-Conformance-Check#176]
With the restructuring of the Redfish v1.7 specification, the assertion numbers as called out by the tool (e.g. "Assertion 6.4.1") no longer match up to the clauses (sections) of the specification.

Recommend that as a quick fix the documentation reflect that the assertion numbers are based on "numbering from Redfish specification v1.x.x".

Longer term, these assertions should be given proper names based on the clause name or area of the testing to remove this issue for future revisions, and also provide a more complete error message.

**Comment by mraineri** [comment]
Near term fix: update the readme to point to the specific version of the spec the assertion numbers match (I think this might be 1.0.2 or 1.1.0).

**Comment by billdodd** [comment]
The current Service-Conformance-Check report section numbers and assertion names are based on spec version **1.0.5**.

**Comment by mraineri** [comment]
Closing; work is being done in https://github.com/DMTF/Redfish-Protocol-Validator for performing validation to the protocol aspects of the spec.
