### ISSUE TITLE
Assertion 6.4.25 fails for resource with transient data that changes etags

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Conformance-Check#191]
I see errors like this printed for every fragment in our tree, even though it seems we do everything correctly. I suspect something in the tool is not handling fragments correctly.

`The services that does not support PUT returns 405.~ GET:/redfish/v1/Chassis/r001u01b/Thermal#/Temperatures/26 failed : HTTP status 200:OK, Expected statuses: [304]~ GET /redfish/v1/Chassis/r001u01b/Thermal#/Temperatures/26 with If-None-Match provided an etag returned status 200:OK which indicates that this resource which does not allow PUT method might have been updated unexpectedly as a result of requesting a PUT method on it previously`

**Comment by billdodd** [comment]
I'm not sure what the issue could be with fragment handling in this assertion. Here is the pseudo-code of the logic related to that failure:

```
do GET request on uri
if etag in response headers:
    do PUT request on uri
    if response status == METHOD_NOT_ALLOWED:
        create If-None-Match request header using etag from GET response
        do GET request on uri (including the If-None-Match header)
        if response status != NOT_MODIFIED:
            emit FAIL message
```

Since the server should be ignoring any fragment in the uri, I don't see how that should affect the results.

The services I tested against do (mostly) behave as the logic above expects. 

Any additional input that would help clarify?

**Comment by blakehilliard** [comment]
Ah, the fact that this listed fragments in the error was a red herring. The problem is actually that these resources have data from sensors that change very often (like the temperature reading of a sensor), so the etag is actually very likely to change over time even if the redfish client has not made any change.

Not sure what the best way is for this tool to handle that! Maybe certain resource like Thermal and Power should be excluded from this particular check?

**Comment by billdodd** [comment]
Ah yes, that makes sense. Excluding Power and Thermal sounds reasonable (blacklisting). Or alternatively, we could limit the resources tested in this assertion via a whitelist.

@mraineri - any comments or preferences?

**Comment by billdodd** [comment]
The blacklist approach seemed straight-forward, so I'm submitting a PR for that. I included Sensors, Thermal, and Power in the resources to skip for this assertion.

**Comment by mraineri** [comment]
I'm okay with that approach for now; whatever helps in the short term
