### ISSUE TITLE
How to clone Repo that is source of Pull Request?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#3]
I would like to test the files from ghazanfarttu:master.
Sorry, I am not enough of a GitHub master to know how to fetch them.
I did a search and did not find the repo.

**Comment by mraineri** [comment]
If you look at the network graph, it points to to the fork that was made.

Ultimately, it comes from here:
https://github.com/ghazanfarttu/Redfish-Service-Conformance-Check.git

**Comment by jbobzin-insyde** [comment]
Thanks
