### ISSUE TITLE
No support to use HTTP only on config file

### ISSUE THREAD

**Issue by ffdarkpenguin** [DMTF/Redfish-Service-Conformance-Check#39]
Hi,
I'm trying to use your tool to check redfish conformance and it does not have support to use HTTP only during the tests. All connections are HTTPS and the tool fails with a lot of:
OPERATIONAL ERROR: GET Request for /redfish/v1/ FAILED with exeption: <class 'ssl.SSLError'>
OPERATIONAL ERROR: GET Request for /redfish FAILED with exeption: <class 'ssl.SSLError'>
OPERATIONAL ERROR: GET Request for /redfish/v1/odata FAILED with exeption: <class 'ssl.SSLError'>
OPERATIONAL ERROR: GET Request for /redfish/v1/$metadata FAILED with exeption: <class 'ssl.SSLError'>

Is is possible to add HTTP only support to your code? Or Is there a non documented way of doing it? Or even is there a documented way of doing it and I was not able to found? If the later please point me to it.

**Comment by mraineri** [comment]
Agreed; the only time HTTPS is required is when credentials are being passed (which is likely limited to a POST to the SessionCollection to start a session).
