### ISSUE TITLE
The check of additionalProperties seems not correct

### ISSUE THREAD

**Issue by cactusjiang** [DMTF/Redfish-Service-Conformance-Check#42]
I got the following error about additionalProperties when I added an annotation @Privileges.OemGetPrivileges in the LogService object.

>Resource: /redfish/v1/Managers/1/LogServices/AuditLog/ of type: LogService.v1_0_4 has Annotation: 'additionalProperties' set to 'False' in its schema document LogService.v1_0_4.json, but additional property: @Privileges.OemGetPrivileges found in resource payload

I know in Redfish specification it says:
>Types annotated with the AdditionalProperties annotation with a value of "False", shall not contain additional properties.

But `Annotations` and `Properties` have different definitions in metadata. It seems that additionalProperties should limit the use of `Properties`, not `Annotations`?

Besides, in the definition of additionaProperties in JSON schema validation document:
https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.4
```
If "additionalProperties" has boolean value false

   In this case, validation of the instance depends on the property set
   of "properties" and "patternProperties". 
```
According to the document if a property (can be an annotation)  is not in "properties" but matches the regular expression defined in patternProperties, even additionalProperties is false, the validation should pass. 

If we follow the above validation, the annotation I added to LogService should pass Redfish-Service-Conformance-Check...

**Comment by billdodd** [comment]
Agreed. Assertion_7_5_11 in the tool should also check against the patternProperties regex.

**Comment by billdodd** [comment]
Thanks for raising this issue and verifying the fix.
