### ISSUE TITLE
The check of rel=describedby in Link Header

### ISSUE THREAD

**Issue by cactusjiang** [DMTF/Redfish-Service-Conformance-Check#43]
In Redfish specification, it says:
>The URL of the JSON Schema for the resource shall be returned with a rel=describedby.

If we look at the Link Header definition in [RFC 5988](https://tools.ietf.org/html/rfc5988), 

`"rel" "=" relation-types`

```
relation-types = relation-type
                 | <"> relation-type *( 1*SP relation-type ) <">
```
According to RFC 5988, both `rel=describedby` and `rel="describedby"` are acceptable, but in current Redfish-Service-Conformance-Check tool it will check `rel=describedby`  and treat `rel="describedby"` as an error. Do you think the tool should be modified to allow `rel="describedby"` ?

**Comment by billdodd** [comment]
It does look like RFC 5988 allows `rel="describedby"`. I'll confirm with the team that they agree and if there should be an update or clarification to the SPMF spec.
