### ISSUE TITLE
Conformance-Check failing tests because is uses old schemas stored in a local dir

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#48]
For Assertion: 6_5_8 (and MAYBE? others) the test uses the local directories that are cloned
with the tool and hold a local copy of schemas.   The problem is that this is a very old snapshot
of schemas and services that use newer schema versions get failures.
FYI--Assertion 6_5_8 test is:
      # Name: Assertion_6_5_8(self, log)                                               
      # Description:    Referencing Other Schemas
      # The service metadata shall include the namespaces for each of the Redfish resource types, 
      # along with the "RedfishExtensions.v1_0_0" namespace.
.
The tool has two local schema directories builtin (for fast access):
./redfish-1.0.0/json-schema/
./redfish-1.0.0/metadata/
The Problem is that these are out of date with respect to http://redfish.dmtf.org/schemas/v1/
There is also the problem that in the Conformance Check tools separates the schemas into
two separate direcdtories above for xml and json.
.
After manually downloading the schemas for redfish.dmtf.org/schemas/v1/ and separating xml 
and json into the two directories, the tests on a service that uses later schemas passed.
SO WE THINK that the only issue is the schema cache built-in to conformanc-check is very old.
.
PROPOSAL:
* add a short  utility (we have) to pull schemas from dmtf, and split the xml and json out into the directories that the test is currently using--in case there are other things also using these.
* a user can clone the repo, then run the utility to update schemas to latest.

Any suggestions?

**Comment by billdodd** [comment]
Good points. We can either keep the local copies of the schemas up to date here in the repo or provide a tool to fetch and install them. Will bring it up with the tools taskforce to see what they think.

**Comment by mraineri** [comment]
Let's make a few changes:
- Pull the schema files from this repo
- Add a .gitignore statement so that we don't commit schema files
- Add a change to the tool to automatically download the latest schema files

**Comment by PhillipWatts1012** [comment]
?I will cleanup a very simple python script for downloading

the schema files and organizing them the way the test wants.

BUT, i would want it optional. I don't want to take the time

to download EVERY time I run the test.



________________________________

**Comment by billdodd** [comment]
Thanks, Phillip. Right, the default won't be to download the files every time.

**Comment by mraineri** [comment]
Will have the tool download schemas automatically if the schema directory is empty; this will allow users to populate the directory with their own schemas as needed, and avoid having to redownload on each use of the tool.
