### ISSUE TITLE
tool does not appear to verify etag is returned for ManagerAccount or if-Match supported

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#50]
The Redfish spec requires that:
* for ManagerAccount, the GET response include a strong etag
Indirectly in the Request Header table, the Redfish spec also requiores that:
* resources that return an etag support if-Match on Patch.
* this of course is thus required for ManagerAccount.
.
So:
* if GET of a ManagerAccount does not return an etag, it should be a FAIL
* if PATCH of a ManagerAccount with if-match header does not process the if-match, it is FAIL
* indirectly, for resources that can be patched, the etag MUST be a strong etag since the RFCs require use of strong etag with if-Match and redfish spec required support of if-match.
* other resources not returning etag are a Should statment and should return a WARN
.
Assertion: 6.4.1 does not do any of these tests currently?
# Name: Assertion_6_4_1(self, log)                                               
# Description:     
# Redfish Services shall understand and be able to process the headers if in the specification the 
# value in the Required Column is set to "Yes" or "Conditional". It covers 6.4.2 as well- WIP   Priyanka

**Comment by billdodd** [comment]
Looking at Assertion_6_4_1, it clearly has not been fully implemented. That function will have to be enhanced to validate the behavior described in 6.4.1.

**Comment by PhillipWatts1012** [comment]
I misunderstood.  The failure to check required etags in manager accounts is actually in 6_5_1

**Comment by PhillipWatts1012** [comment]
I am not permitted to do pull request. I would suggest this insert around 
line 2449, assertion 6_5_1
```
        # manage assertion status
        assertion_status = log.status_fixup(assertion_status,assertion_status_)

    ## NEW
        if assertion_status_ != log.PASS:
            continue
        else:
            assertion_status = response_header_check(headers, relative_uris[relative_uri], log)
            if '@odata.type' not in json_payload:
                continue
            if 'ManagerAccount.' in json_payload['@odata.type']:
                if 'etag' not in [h.lower() for h in headers]:
                    print (relative_uris[relative_uri],'Manager Account missing etag')
                    assertion_status = log.FAIL
    ## END NEW
```

**Comment by billdodd** [comment]
Thanks, Phillip.

I looked at the spec where it talks about the requirement for returning an etag header for GET requests for ManagerAccount resources. This is section **6.1.5. ETags**. Then I went to the tool to double-check what test assertion should be checking this. I believe it is actually `Assertion_6_1_14()`. It currently just checks for the etag header on GET requests and issues a warning if not found. And as you noted, for ManagerAccount resources, it should be issuing an error if the etag header is missing (which it is not doing).

I'll make an update to `Assertion_6_1_14()` to add that check.

BTW, to help see how the test assertions map to the spec sections, have a look at the .xlsx report generated by the tool. For example, here is a screenshot of the 2 rows in the spreadsheet for spec section  **6.1.5. ETags**:

![screen shot 2017-12-21 at 2 39 51 pm](https://user-images.githubusercontent.com/3341721/34274303-94922c70-e65d-11e7-8765-8e7d3e5ec66d.png)

You can see the target spec section in the first row, second column ("Section 6.1.5 :ETags"). And the corresponding test assertion is in the second row, first column ("6.1.14").
