### ISSUE TITLE
Assertion 6_5_6_9 appears to be a URI misconception

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#55]
---> Assertion: 6.5.6.9
/redfish/v1/
 GET:/redfish/v1 failed : HTTP status 200:OK, Expected status 404:Not Found
The test strips off the trailing slash which leaves a valid URI
and therefore The GET succeeds with a 200.
The test expects a 404.

**Comment by billdodd** [comment]
Looks like this assertion was started but not completed. It doesn't do what the assertion comment says it does. It purportedly should be sending a request that results in a `400 Bad Request` with an extended error in the response body. (See spec section **6.5.2. Status codes** and the `400 Bad Request` entry in the table.)

Need to investigate further how this can be tested.
