### ISSUE TITLE
Annotation confusion - extension to ISSUE 56

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#57]
Also in 7.5.3 thru 7.5.15 there LOTS of failures on
LongDescription missing.
Those actually ARE missing in many of the schema.
But we are not aware of any LongDescription requirement.
However,
perhaps  DSP0266 | 1.3.0 says they are required.
Opinion?

**Comment by billdodd** [comment]
See my comment in issue #56

**Comment by billdodd** [comment]
SPMF Issue filed. Think this issue can be closed now (also see issue #56).

**Comment by mraineri** [comment]
Closing; this issue has been migrated to the SPMF repo for tracking the updates to schemas.
