### ISSUE TITLE
Assertion 6_1_8_4 warns that root response header does not allow DELETE

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#59]
---> Assertion: 6.1.8.4
~ note: the header returned from GET /redfish/v1/AccountService/Accounts/root do not indicate support for DELETE

  "allow": "GET,HEAD,PATCH"
}
We do not allow DELETE of root. Does redfish?

**Comment by billdodd** [comment]
Redfish doesn't disallow the deletion of any particular account (including root). So, yes it is allowed by Redfish.

But it's also OK for a service to not allow it.

**Comment by mraineri** [comment]
1/25: It's valid to not allow DELETE on a resource (even if the schema says a resource is deleteable). However, this should not produce an error; only a warning at most.
