### ISSUE TITLE
[New Version in Pull]  Exception Processing Memory.AllowedSpeedsMhz

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#6]
The proposed pull version consistently has exception on Memory.AllowedSpeedsMhz[2666].
The exception is in routine process_list(), line 581 of rf_sut.py.
The program is looking for @odata.id in the 2666 numeric array element.
I have updated the local schema directory with files from 2016.3.

Here is failing page returned by the service.
```
{
    "@odata.context": "/redfish/v1/$metadata#Memory.Memory",
    "@odata.id": "/redfish/v1/Systems/BQWT64900010/Memory/Memory1",
    "@odata.type": "#Memory.v1_1_0.Memory",
    "Id": "Memory1",
    "Name": "Memory 1",
    "Description": "System Memory",
    "MemoryType": "DRAM",
    "MemoryDeviceType": "DDR4",
    "BaseModuleType": "RDIMM",
    "CapacityMiB": 8192,
    "DataWidthBits": 64,
    "Manufacturer": "Micron",
    "SerialNumber": "14F81054",
    "PartNumber": "18ASF1G72PZ-2G6B1   ",
    "AllowedSpeedsMHz": [
        2666
    ],
    "RankCount": 1,
    "DeviceLocator": "CPU0_DIMM_F1",
    "ErrorCorrection": "MultiBitECC",
    "OperatingSpeedMhz": 2666,
    "Metrics": {
        "@odata.id": "/redfish/v1/Systems/BQWT64900010/Memory/Memory1/MemoryMetrics"
    },
    "Status": {
        "State": "Enabled",
        "Health": "OK",
        "HealthRollup": "OK"
    }
}
```

**Comment by mraineri** [comment]
Seems like this might be scope creep in the tool; the tool should be verifying the normative language in the spec, while the Service Validator tool verifies the JSON payloads conform to the schema.

**Comment by mraineri** [comment]
Would like Bill and Tomas to work directly with Jeff to get some access to the system to debug the branch.

**Comment by jbobzin-insyde** [comment]
send me private email at jeff.bobzin@insyde.com and I will reply with IP and logon

**Comment by billdodd** [comment]
Jeff - an update:

I fixed the error with the "AllowedSpeedsMHz" list of integers. And a number of other errors I've found subsequently. I'm still in a loop of "run test -> get error -> fix error -> repeat". As soon as I get a clean run I'll commit my changes to the pending Pull Request.

**Comment by billdodd** [comment]
Fix merge via https://github.com/DMTF/Redfish-Service-Conformance-Check/pull/2
