### ISSUE TITLE
Assertion: 6.4.32 fails on 204, expects 200

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#62]
https://github.com/DMTF/spmf/blob/master/Specification.md
Data modification requests
Actions (POST)
HTTP Status Code 200 indicates the Action request was successfully processed, with the JSON message body as described in Error Responses and providing a message indicating success or any additional relevant messages.
HTTP Status Code 204 indicates the Action is successful and is returned without a message body.

Therefore if no data, 204 should pass.

**Comment by billdodd** [comment]
Yes, looks like 204 should be fine.

Seems like in most cases, any time a 200 response is OK, a 204 would also be OK. It wouldn't be OK of course in cases where a response is required.

Thinking that the response_status_check() function in the tool should be modified to allow both 200 and 204 in the case where an explicit response code is not specified.

**Comment by PhillipWatts1012** [comment]
?Not sure how it should be coded, BUT, seems no data returned and 204 are equal.

________________________________
