### ISSUE TITLE
Need more defense - 6.5.40

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#68]
---> Assertion: 6.5.40  
File "/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/TEST_protocol_details.py", line 4878, in Assertion_6_5_40
    if 'error' in json_payload : 
TypeError: 'str' does not support the buffer interface

for some reason, failed PATCH is returning a "byte string" rather than a string.
I suggest adding this line:
 **json_payload = str(json_payload)**

Or perhaps better would be to insure GET and PATCH always
return the json_payload as type str.

**Comment by PhillipWatts1012** [comment]
This issue has not been addressed. It still causes an exception.

**Comment by billdodd** [comment]
Can you provide the traceback of the exception?

**Comment by PhillipWatts1012** [comment]
This issue has not been addressed. It still causes an exception.

**Comment by PhillipWatts1012** [comment]
if 'error' in json_payload :
TypeError: 'str' does not support the buffer interface

**Comment by billdodd** [comment]
Ah, sorry for the confusion. I assumed you were testing the PR (#75 ). The code in master doesn't have the fix yet. The PR with the fix should get merged during the tools TF call this Thursday.

**Comment by PhillipWatts1012** [comment]
Thanks!
