### ISSUE TITLE
Error while running conformance check tool

### ISSUE THREAD

**Issue by veedu** [DMTF/Redfish-Service-Conformance-Check#7]
Hi Developers,
Our organization is using Conformance check tool for testing our redfish service. We are first testing it with standard redfish mockup server and facing the following error:

[root@aspenvail01 Redfish-Service-Conformance-Check-master]# python3 rf_client.py
Setting up Redfish Service Check Tool Revision: 07.11.16 : vidhyag:127.0.0.1:8000
url.scheme http url.ip 127.0.0.1:8000
http only
url.scheme http url.ip 127.0.0.1:8000
http only
url.scheme http url.ip 127.0.0.1:8000
http only

Collecting all relative uris from Service Root: /redfish/v1/
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems :/redfish/v1/Systems
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1 :/redfish/v1/Systems/2M220100SL
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices :/redfish/v1/Systems/2M220100SL/LogServices
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices_Members_1 :/redfish/v1/Systems/2M220100SL/LogServices/SEL
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices_Members_1_Entries :/redfish/v1/Systems/2M220100SL/LogServices/SEL/Entries
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices_Members_1_Entries_Members_1 :/redfish/v1/Systems/2M220100SL/LogServices/SEL/Entries/1
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices_Members_1_Entries_Members_1_Links_OriginOfCondition :/redfish/v1/Chassis/1/Thermal
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Systems_Members_1_LogServices_Members_1_Entries_Members_2 :/redfish/v1/Systems/2M220100SL/LogServices/SEL/Entries/2
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_SessionService :/redfish/v1/SessionService
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_SessionService_Sessions :/redfish/v1/SessionService/Sessions
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_SessionService_Sessions_Members_1 :/redfish/v1/SessionService/Sessions/SESSION123456
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Chassis :/redfish/v1/Chassis
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Chassis_Members_1 :/redfish/v1/Chassis/A33
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Managers :/redfish/v1/Managers
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Managers_Members_1 :/redfish/v1/Managers/bmc
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Managers_Members_1_NetworkProtocol :/redfish/v1/Managers/bmc/NetworkProtocol
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Managers_Members_1_EthernetInterfaces :/redfish/v1/Managers/bmc/EthernetInterfaces
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_Managers_Members_1_EthernetInterfaces_Members_1 :/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService :/redfish/v1/AccountService
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Roles :/redfish/v1/AccountService/Roles
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Roles_Members_1 :/redfish/v1/AccountService/Roles/Admin
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Roles_Members_2 :/redfish/v1/AccountService/Roles/Operator
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Roles_Members_3 :/redfish/v1/AccountService/Roles/ReadOnlyUser
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Accounts :/redfish/v1/AccountService/Accounts
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Accounts_Members_1 :/redfish/v1/AccountService/Accounts/root
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Accounts_Members_2 :/redfish/v1/AccountService/Accounts/jane
url.scheme http url.ip 127.0.0.1:8000
http only
Root Service_AccountService_Accounts_Members_3 :/redfish/v1/AccountService/Accounts/john
url.scheme http url.ip 127.0.0.1:8000
http only

Serializing SUT metadata document: /redfish/v1/$metadata ...
url.scheme http url.ip 127.0.0.1:8000
http only
Traceback (most recent call last):
  File "rf_client.py", line 764, in <module>
    main()
  File "rf_client.py", line 756, in main
    sut = setup_tool(sut_prop)
  File "rf_client.py", line 739, in setup_tool
    if setup_sut_obj(sut):
  File "rf_client.py", line 707, in setup_sut_obj
    metadata_document_structure = sut.parse_metadata_document(sut.Redfish_URIs['Service_Metadata_Doc'])
  File "/home/vidhyag/Redfish-Service-Conformance-Check-master/rf_sut.py", line 458, in parse_metadata_document
    csdl_schema_model.serialize_schema(schema_payload = json_payload, schema_uri= metadata_uri)
  File "/home/vidhyag/Redfish-Service-Conformance-Check-master/schema.py", line 777, in serialize_schema
    schema_root = ET.fromstring(schema_payload)
  File "/usr/lib64/python3.4/xml/etree/ElementTree.py", line 1335, in XML
    parser.feed(text)
TypeError: 'dict' does not support the buffer interface

I changed http__req_resp,   url = urlparse("http://" + sut_prop['DnsName'] + resource_uri) from 'https' to http. Can you let me know if anything else is required?

**Comment by jbobzin-insyde** [comment]
I am a user not a developer, but in my recent examination of this tool I found no way to use with mockup server.
The Conformance tool depends on writes to pages which mockup server will accept but not process.

In contrast, the Redfish-Service-Validator can easily be configured to be use with mockup server.

That said, even with a real operating service, I am not able to see Conformance tool complete.  I get a similar exception.
I think this tool is not quite ready for use.

BTW – are you using the github current image or the pending pull request? The current image in github master is old…

---Jeff

**Comment by billdodd** [comment]
Hi @veedu - thanks for the report.

A few notes:

- As Jeff noted, the tool is really meant to use against a live system rather than a  mockup. It does lots of POST, DELETE, and other operations that are not typically supported by mockups. It also assumes the use of https (it tests security assertions that require the use of basic auth creds over an https connection).
- As Jeff also noted, the version of the tool in the master branch is old. We're in the process of merging in the latest development version of the tool into master. But that will probably take a few more days at a minimum (a fair number of bugs have been found that need to be squashed).
- For the error you are getting: The error is happening when trying to parse the CSDL schema at /redfish/v1/$metadata. Does your mockup return a valid schema from that uri?

I'd suggest waiting a bit until the pending Pull request is merged. Then try again against a live system.

**Comment by billdodd** [comment]
Jeff,

In commit d87d88b I have fixes that should allow a complete run against your test system. (It ran to completion for me.)

I'm still working my way through some more errors on a couple of other systems, so I expect some more updates soon. But thought you might want to give the current Pull Request a try.

**Comment by veedu** [comment]
Thanks all for the reply. I will try out with new merge. Our service's root is from /redfish/v1 but the tool is sending GET request for /redfish. Can any one please let me know if implementation of /redfish is required. If not is there any work around in the tool to skip requests for some properties which our service doesn't support.

**Comment by billdodd** [comment]
Yes, it is required that a service implement /redfish. In the spec, at the bottom of section **6.2 Protocol version**, it says:

> A GET on the resource "/redfish" shall return the following body:
> 
> ```
> {
>     "v1": "/redfish/v1/"
> }
> ```

That said, it seems like the tool should report that the assertion failed and then carry on assuming a version of v1. And in general, it should do that for other properties a service doesn't support (report the failure and continue processing).

**Comment by billdodd** [comment]
Hi Vidhya,

After investigating the code, I will use this issue to make a change to the tool so that it can continue on with assertion testing even if the service does not return a response to the '/redfish' uri. It will, of course, still report a conformance failure. But it will be able to continue on with testing the other assertions.

**Comment by mraineri** [comment]
Closing; fixed in PR #8
