### ISSUE TITLE
Assert 6.1.8.1 requires recommended header Allow

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#76]
Redfish Spec section 6.5.1 in the table for Response Headers, for the header Allow, has this sentence - 
"Should be returned with any GET or HEAD operation to indicate the other allowable operations for this resource."

Since this is a 'Should' the header Allow return with get is recommended but not required. But Test 6.1.8.1 fails and this leads to failure later in 6.1.8.4 
Or am I reading the code wrong?
log below

---> Assertion: 6.1.8.1
~ note: the header returned from GET /redfish/v1/SessionService/Sessions do not indicate support for POST
{
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "server": "lighttpd/1.4.48",
  "x-ua-compatible": "IE=11",
  "content-length": "282",
  "date": "Mon, 05 Jan 1987 19:12:59 GMT",
  "content-type": "application/json",
  "x-frame-options": "SAMEORIGIN",
  "x-xss-protection": "1; mode=block"
}
Assertion Description: b'\nPOST\nObject create, Object action, Eventing\nYes\n'
<--- Assertion 6.1.8.1: FAIL

**Comment by jbobzin-insyde** [comment]
several other asserts also assume Allow returned by GET
6.4.2.2,
6.4.23, 6.4.26,

**Comment by billdodd** [comment]
And there are even more assertions with this issue. I think the full list is:

6.1.8.1, 6.1.8.3, 6.1.8.4,
6.4.2.2, 6.4.18, 6.4.21, 6.4.23, 6.4.24, 6.4.24.xml, 6.4.25, 6.4.26, 6.4.27, 6.4.30,
6.5.2.6, 6.5.6.13, 6.5.40
