### ISSUE TITLE
6.4.3 Code assumes Action has a "target" but "target" is not clearly named as requirement

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#77]
Line 1995 in TEST_protocol_details
`              log.assertion_log('line', 'Action %s found' % (json_payload['Actions']['#ComputerSystem.Reset']['target']))`
generates KeyError program exception if "target" not present.
But spec has this line in 6.4.4.7 which seems to allow "target" to be omitted- 

Custom actions are requested on a resource by sending the HTTP POST method to the URI of the
action. If the actions property within a resource **does not specify a target property**, then the URI of an
action shall be of the form:

But section 6.5.4.7.1 does not mention missing "target" so it is not 100% clear if required or not.

**Comment by billdodd** [comment]
Interesting. Section 6.5.4.7.1 could be read as requiring the target property:

> The value of the property shall be a JSON object containing a property named "target" whose value is a relative or absolute URL used to invoke the action.

So as you say, not completely clear.

In any case, the assertion should be updated to avoid the exception.

And may also need to be updated to generate the target uri if the target property is missing. Will see what the tools TF folks say about that.

**Comment by jbobzin-insyde** [comment]
I noted this because an implementer added an action and user string "Target" instead of "target" which is clearly our bug. But I thought the KeyError program crash should be noted.

And this led to the spec question. In my design docs I have always thought "target" should appear and I would not object to making it mandatory. But it seems ambiguous today.

**Comment by mraineri** [comment]
Having an empty "Actions" object, or not even supporting the "Actions" object is valid; so it's legal to not have "#ComputerSystem.Reset" in the response.

However, I think you have found conflicting requirements in the spec... It looks like "target" is a shall statement in "6.5.4.7.1 Action representation", but is a "should" statement in "6.4.4.7. Actions (POST)". I'll file an issue on this in the SPMF repo.

**Comment by billdodd** [comment]
I included the corrections for this issue in PR #93, which was merged last week. We should be able to close this issue.

**Comment by mraineri** [comment]
Closed; addressed in the above PR
