### ISSUE TITLE
Assertion 6.5.8

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#78]
This is a new failure. maybe in the last month.
It may have to do with the addition of the automatic
download of Schemas. For several of the resources,
multiple json versions are downloaded.
It appears that if our metadata does not reference  all
of the schemas, then it will FAIL.
I reorganized the output. The list below is a DIFF. 
In other words the list of "missing references".

DIFF {'Chassis.v1_5_2', 'Chassis.v1_1_2', 'ActionInfo.v1_0_2', 'AttributeRegistry.v1_1_0', 'AttributeRegistry', 'BootOptionCollection', 'ActionInfo', 'BootOption', 'Chassis.1.1.0', 'Chassis.v1_0_3', 'AccountService.v1_2_1', 'Chassis.v1_0_6', 'Bios.v1_0_1', 'CompositionService', 'ActionInfo.v1_0_0', 'Chassis.v1_0_2', 'Chassis.v1_1_4', 'Chassis.v1_0_4', 'Chassis.v1_0_0', 'CollectionCapabilities.v1_0_0', 'CollectionCapabilities', 'Bios.v1_0_2', 'AccountService.v1_0_5', 'Chassis.v1_5_0', 'AccountService.v1_1_1', 'AccountService.v1_1_0', 'ActionInfo.v1_0_1', 'Chassis.v1_2_4', 'AttributeRegistry.v1_0_1', 'Chassis.v1_1_5', 'AttributeRegistry.v1_0_0', 'Chassis.v1_2_0', 'ComputerSystem.v1_0_0', 'AttributeRegistry.v1_1_1', 'Bios', 'Chassis.v1_1_3', 'Chassis.v1_0_1', 'ComputerSystem.1.0.1', 'Assembly.v1_0_0', 'AccountService.v1_0_3', 'Chassis.v1_3_0', 'Chassis.v1_3_1', 'Chassis.v1_4_2', 'ActionInfo.v1_0_3', 'AccountService.v1_2_2', 'AccountService.v1_2_0', 'AttributeRegistry.v1_0_2', 'Chassis.v1_6_0', 'Assembly', 'CompositionService.v1_0_0', 'ComputerSystem.1.0.0', 'Chassis.v1_4_1', 'Chassis.v1_2_1', 'Chassis.1.0.0', 'Chassis.v1_2_3', 'Chassis.v1_5_1', 'Chassis.1.0.1', 'Chassis.v1_1_6', 'Chassis.v1_4_3', 'Chassis.v1_2_2', 'AccountService.v1_0_4', 'Bios.v1_0_0', 'AccountService.v1_0_2', 'Chassis.v1_1_0', 'Chassis.v1_3_3', 'AccountService.v1_1_2', 'Bios.v1_0_3', 'BootOption.v1_0_0', 'CompositionService.v1_0_1', 'Chassis.v1_3_4', 'AccountService.1.0.0', 'Chassis.v1_0_5', 'Chassis.v1_3_2'}

**Comment by billdodd** [comment]
Yes, it doesn't look like the code in Assertion_6_5_8() is doing the right thing. For one thing, I don't think this `if` statement is doing what was intended (txt_files is the list of all schemas from redfish.dmtf.org and list1 is the list of schemas referenced by the resources on the service):

```
    if list1 in txt_files:
         assertion_status = log.PASS
    else :
        assertion_status = log.FAIL
```

It should be using set() operations for the test instead.

But before debugging it further, it seems like this assertion is already better covered by the service-validator, so maybe it is better just to disable it here?

**Comment by billdodd** [comment]
For reference, here is the spec requirement that Assertion_6_5_8() is supposed to be testing:

> 6.5.3.1.1. Referencing other schemas
> 
> The service metadata shall include the namespaces for each of the Redfish resource types, along with the "RedfishExtensions.v1_0_0" namespace. These references may use the standard URI for the hosted Redfish Schema definitions (i.e., on http://redfish.dmtf.org/schemas) or a URI to a local version of the Redfish Schema that shall be identical to the hosted version.
