### ISSUE TITLE
Does Redfish JSON allow single quote?

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#80]
I noticed this line in 6_4_32
rq_body = {'ResetType': 'ForceOff'}

I checked some web sites that said JSON should use double quotes.
Did we relax this for Redfish?

Or maybe I am reading the python wrong. But in my test the single quotes made it out to the system under test (and failed)

**Comment by billdodd** [comment]
That code is Python and single or double quotes are valid for Python
strings. The Python representation gets converted to JSON before being sent
in the request, so it will be sent with double quotes.

**Comment by jbobzin-insyde** [comment]
I thought that too.  I will debug deeper tomorrow. Maybe I guessed wrong about why.

**Comment by jbobzin-insyde** [comment]
Sorry, there is a problem but I debugged wrong. See next issue.
