### ISSUE TITLE
Questions while pretending to be a naive user

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#86]
This tool is public and I suggest we need to step back and make some effort to make it more understandable.

Starting with 6.1.3 and 6.1.5 there are a many lines in the output with no Column A highlight color.  Reading the source we know some of these are unimplemented assertions. Are they not-yet-implemented or never-expected asserts? Does the no-color ever mean skipped?   How should the status be communicated to the naive tester?  

Does this confusion come from the choice to have the annotated design document (spread sheet) serve as the output delivery? Maybe there should be a column indicating the code status?

Or, maybe change all of the assert lines to hidden and unhide when a test is started?

6.5.2.7 -.9 have the comment "Tested with the Dell Server" which is hard to understand given there is no code. Does this maybe mean someone once tested by hand? What does this have to do with my test run?

It is my impression that there are some tests of the schema definition rules mixed in that do not depend on the system under test.  Fail on 7.5.16 is an example.   Is verifying the schema really something we want this tool to do?  Since the tool downloads the latest schema from common site would not every system get the same results?  I suggest the schema checking asserts be moved to a separate tool. This tool takes too long to run without everyone checking the same schema.

ACCO101 appears to be the last test but the spread sheet has 1200+ more tests listed.

How much of the long run time is due to the overhead of opening and editing a spread sheet? Is this really the output style we want?

**Comment by mraineri** [comment]
Closing; work is being done in https://github.com/DMTF/Redfish-Protocol-Validator for performing validation to the protocol aspects of the spec.
