### ISSUE TITLE
Assert 6.5.1 looking for optional headers

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#88]
FAIL on missing link and allow response header is not correct.
The table in the spec at 6.5.1 says "Yes" in "Required" column but the "Description" column explains that "Yes" means "Sometimes"

I may be wrong about link, someone more expert should comment on when link is required.

**Comment by billdodd** [comment]
From reading **6.5.1.1. Link Header**, my interpretation is that a Link header with a `rel=describedby` must (shall) be returned from GET and HEAD operations. So I think the test assertion is correct in requiring the Link header.

For the Allow header, this is optional for GET, so agree that the assertion should not be requiring it.
