### ISSUE TITLE
Possible Coding Error in 6_5_23_1

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Service-Conformance-Check#90]
I am seeing random failures of this test.
I believe it is because these lines are out of order - 
`    count = 0 `
`    for relative_uri in relative_uris:`
count is used below to get a count of member_array, but the the initialize of count is out of the for loop. So the starting point is random based on last page checked.
`    count = count+1`
This loop
`for m in member_array:` 
is poor python - should really use len(member_array)

**Comment by billdodd** [comment]
See also issue #81
